java -jar swagger-codegen-cli-3.0.25.jar generate \
  -i swagger.json \
  --api-package client.api \
  --model-package client.model \
  --invoker-package client.invoker \
  --group-id com.exemplo \
  --artifact-id exemplo-codegen \
  --artifact-version 0.0.1-SNAPSHOT \
  -l java \
  --library resttemplate \
  -o output
