/*
 * api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package logic.smartmind.client.api;

import logic.smartmind.client.model.ParamVariavelNotificacao;
import logic.smartmind.client.model.ParamVariavelNotificacao2;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ParamvariavelnotificacaoApi
 */
@Ignore
public class ParamvariavelnotificacaoApiTest {

    private final ParamvariavelnotificacaoApi api = new ParamvariavelnotificacaoApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paramvariavelnotificacaoCodigoDeleteTest() {
        Integer codigo = null;
        api.paramvariavelnotificacaoCodigoDelete(codigo);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paramvariavelnotificacaoCodigoGetTest() {
        Integer codigo = null;
        ParamVariavelNotificacao response = api.paramvariavelnotificacaoCodigoGet(codigo);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paramvariavelnotificacaoCodigoPatchTest() {
        Integer codigo = null;
        ParamVariavelNotificacao2 body = null;
        api.paramvariavelnotificacaoCodigoPatch(codigo, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paramvariavelnotificacaoGetTest() {
        List<ParamVariavelNotificacao> response = api.paramvariavelnotificacaoGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void paramvariavelnotificacaoPostTest() {
        ParamVariavelNotificacao2 body = null;
        api.paramvariavelnotificacaoPost(body);

        // TODO: test validations
    }
    
}
