/*
 * api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package logic.smartmind.client.api;

import logic.smartmind.client.model.Setor;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SetorApi
 */
@Ignore
public class SetorApiTest {

    private final SetorApi api = new SetorApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setorCodigoDeleteTest() {
        Integer codigo = null;
        api.setorCodigoDelete(codigo);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setorCodigoGetTest() {
        Integer codigo = null;
        Setor response = api.setorCodigoGet(codigo);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setorCodigoPatchTest() {
        Integer codigo = null;
        Setor body = null;
        api.setorCodigoPatch(codigo, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setorGetTest() {
        List<Setor> response = api.setorGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setorPostTest() {
        Setor body = null;
        api.setorPost(body);

        // TODO: test validations
    }
    
}
