/*
 * api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package logic.smartmind.client.api;

import logic.smartmind.client.model.Usuario;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsuarioApi
 */
@Ignore
public class UsuarioApiTest {

    private final UsuarioApi api = new UsuarioApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usuarioGetTest() {
        List<Usuario> response = api.usuarioGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usuarioLoginDeleteTest() {
        String login = null;
        api.usuarioLoginDelete(login);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usuarioLoginGetTest() {
        String login = null;
        Usuario response = api.usuarioLoginGet(login);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usuarioLoginPatchTest() {
        String login = null;
        Usuario body = null;
        api.usuarioLoginPatch(login, body);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void usuarioPostTest() {
        Usuario body = null;
        api.usuarioPost(body);

        // TODO: test validations
    }
    
}
