/*
 * api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package logic.smartmind.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * Assets
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-25T12:20:00.812-03:00")
public class Assets {
  @JsonProperty("Name")
  private String name = null;

  @JsonProperty("ExternalId")
  private String externalId = null;

  @JsonProperty("Description")
  private String description = null;

  @JsonProperty("TypeId")
  private String typeId = null;

  @JsonProperty("ParentId")
  private String parentId = null;

  @JsonProperty("Timezone")
  private String timezone = null;

  @JsonProperty("TenantId")
  private String tenantId = null;

  @JsonProperty("SubTenant")
  private String subTenant = null;

  @JsonProperty("T2Tenant")
  private String t2Tenant = null;

  @JsonProperty("AssetId")
  private String assetId = null;

  @JsonProperty("Deleted")
  private DateTime deleted = null;

  @JsonProperty("Etag")
  private Integer etag = null;

  @JsonProperty("Href")
  private String href = null;

  @JsonProperty("IsNew")
  private Boolean isNew = null;

  @JsonProperty("order")
  private Integer order = null;

  @JsonProperty("statusColor")
  private String statusColor = null;

  @JsonProperty("Unidade")
  private String unidade = null;

  @JsonProperty("Setor")
  private String setor = null;

  @JsonProperty("active")
  private Boolean active = null;

  @JsonProperty("offLineTime")
  private Long offLineTime = null;

  @JsonProperty("dateTimeOffLine")
  private DateTime dateTimeOffLine = null;

  @JsonProperty("TwinType")
  private String twinType = null;

  @JsonProperty("Platform")
  private String platform = null;

  public Assets name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Assets externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * Get externalId
   * @return externalId
  **/
  @ApiModelProperty(value = "")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public Assets description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Assets typeId(String typeId) {
    this.typeId = typeId;
    return this;
  }

   /**
   * Get typeId
   * @return typeId
  **/
  @ApiModelProperty(value = "")
  public String getTypeId() {
    return typeId;
  }

  public void setTypeId(String typeId) {
    this.typeId = typeId;
  }

  public Assets parentId(String parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  @ApiModelProperty(value = "")
  public String getParentId() {
    return parentId;
  }

  public void setParentId(String parentId) {
    this.parentId = parentId;
  }

  public Assets timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  @ApiModelProperty(value = "")
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  public Assets tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @ApiModelProperty(value = "")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public Assets subTenant(String subTenant) {
    this.subTenant = subTenant;
    return this;
  }

   /**
   * Get subTenant
   * @return subTenant
  **/
  @ApiModelProperty(value = "")
  public String getSubTenant() {
    return subTenant;
  }

  public void setSubTenant(String subTenant) {
    this.subTenant = subTenant;
  }

  public Assets t2Tenant(String t2Tenant) {
    this.t2Tenant = t2Tenant;
    return this;
  }

   /**
   * Get t2Tenant
   * @return t2Tenant
  **/
  @ApiModelProperty(value = "")
  public String getT2Tenant() {
    return t2Tenant;
  }

  public void setT2Tenant(String t2Tenant) {
    this.t2Tenant = t2Tenant;
  }

  public Assets assetId(String assetId) {
    this.assetId = assetId;
    return this;
  }

   /**
   * Get assetId
   * @return assetId
  **/
  @ApiModelProperty(value = "")
  public String getAssetId() {
    return assetId;
  }

  public void setAssetId(String assetId) {
    this.assetId = assetId;
  }

  public Assets deleted(DateTime deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  @ApiModelProperty(value = "")
  public DateTime getDeleted() {
    return deleted;
  }

  public void setDeleted(DateTime deleted) {
    this.deleted = deleted;
  }

  public Assets etag(Integer etag) {
    this.etag = etag;
    return this;
  }

   /**
   * Get etag
   * @return etag
  **/
  @ApiModelProperty(value = "")
  public Integer getEtag() {
    return etag;
  }

  public void setEtag(Integer etag) {
    this.etag = etag;
  }

  public Assets href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @ApiModelProperty(value = "")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public Assets isNew(Boolean isNew) {
    this.isNew = isNew;
    return this;
  }

   /**
   * Get isNew
   * @return isNew
  **/
  @ApiModelProperty(value = "")
  public Boolean getIsNew() {
    return isNew;
  }

  public void setIsNew(Boolean isNew) {
    this.isNew = isNew;
  }

  public Assets order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @ApiModelProperty(value = "")
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public Assets statusColor(String statusColor) {
    this.statusColor = statusColor;
    return this;
  }

   /**
   * Get statusColor
   * @return statusColor
  **/
  @ApiModelProperty(value = "")
  public String getStatusColor() {
    return statusColor;
  }

  public void setStatusColor(String statusColor) {
    this.statusColor = statusColor;
  }

  public Assets unidade(String unidade) {
    this.unidade = unidade;
    return this;
  }

   /**
   * Get unidade
   * @return unidade
  **/
  @ApiModelProperty(value = "")
  public String getUnidade() {
    return unidade;
  }

  public void setUnidade(String unidade) {
    this.unidade = unidade;
  }

  public Assets setor(String setor) {
    this.setor = setor;
    return this;
  }

   /**
   * Get setor
   * @return setor
  **/
  @ApiModelProperty(value = "")
  public String getSetor() {
    return setor;
  }

  public void setSetor(String setor) {
    this.setor = setor;
  }

  public Assets active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public Assets offLineTime(Long offLineTime) {
    this.offLineTime = offLineTime;
    return this;
  }

   /**
   * Get offLineTime
   * @return offLineTime
  **/
  @ApiModelProperty(value = "")
  public Long getOffLineTime() {
    return offLineTime;
  }

  public void setOffLineTime(Long offLineTime) {
    this.offLineTime = offLineTime;
  }

  public Assets dateTimeOffLine(DateTime dateTimeOffLine) {
    this.dateTimeOffLine = dateTimeOffLine;
    return this;
  }

   /**
   * Get dateTimeOffLine
   * @return dateTimeOffLine
  **/
  @ApiModelProperty(value = "")
  public DateTime getDateTimeOffLine() {
    return dateTimeOffLine;
  }

  public void setDateTimeOffLine(DateTime dateTimeOffLine) {
    this.dateTimeOffLine = dateTimeOffLine;
  }

  public Assets twinType(String twinType) {
    this.twinType = twinType;
    return this;
  }

   /**
   * Get twinType
   * @return twinType
  **/
  @ApiModelProperty(value = "")
  public String getTwinType() {
    return twinType;
  }

  public void setTwinType(String twinType) {
    this.twinType = twinType;
  }

  public Assets platform(String platform) {
    this.platform = platform;
    return this;
  }

   /**
   * Get platform
   * @return platform
  **/
  @ApiModelProperty(value = "")
  public String getPlatform() {
    return platform;
  }

  public void setPlatform(String platform) {
    this.platform = platform;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Assets assets = (Assets) o;
    return Objects.equals(this.name, assets.name) &&
        Objects.equals(this.externalId, assets.externalId) &&
        Objects.equals(this.description, assets.description) &&
        Objects.equals(this.typeId, assets.typeId) &&
        Objects.equals(this.parentId, assets.parentId) &&
        Objects.equals(this.timezone, assets.timezone) &&
        Objects.equals(this.tenantId, assets.tenantId) &&
        Objects.equals(this.subTenant, assets.subTenant) &&
        Objects.equals(this.t2Tenant, assets.t2Tenant) &&
        Objects.equals(this.assetId, assets.assetId) &&
        Objects.equals(this.deleted, assets.deleted) &&
        Objects.equals(this.etag, assets.etag) &&
        Objects.equals(this.href, assets.href) &&
        Objects.equals(this.isNew, assets.isNew) &&
        Objects.equals(this.order, assets.order) &&
        Objects.equals(this.statusColor, assets.statusColor) &&
        Objects.equals(this.unidade, assets.unidade) &&
        Objects.equals(this.setor, assets.setor) &&
        Objects.equals(this.active, assets.active) &&
        Objects.equals(this.offLineTime, assets.offLineTime) &&
        Objects.equals(this.dateTimeOffLine, assets.dateTimeOffLine) &&
        Objects.equals(this.twinType, assets.twinType) &&
        Objects.equals(this.platform, assets.platform);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, externalId, description, typeId, parentId, timezone, tenantId, subTenant, t2Tenant, assetId, deleted, etag, href, isNew, order, statusColor, unidade, setor, active, offLineTime, dateTimeOffLine, twinType, platform);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Assets {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    subTenant: ").append(toIndentedString(subTenant)).append("\n");
    sb.append("    t2Tenant: ").append(toIndentedString(t2Tenant)).append("\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    etag: ").append(toIndentedString(etag)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    isNew: ").append(toIndentedString(isNew)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    statusColor: ").append(toIndentedString(statusColor)).append("\n");
    sb.append("    unidade: ").append(toIndentedString(unidade)).append("\n");
    sb.append("    setor: ").append(toIndentedString(setor)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    offLineTime: ").append(toIndentedString(offLineTime)).append("\n");
    sb.append("    dateTimeOffLine: ").append(toIndentedString(dateTimeOffLine)).append("\n");
    sb.append("    twinType: ").append(toIndentedString(twinType)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

