/*
 * api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package logic.smartmind.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * AssetNotificationLog
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-25T12:20:00.812-03:00")
public class AssetNotificationLog {
  @JsonProperty("AssetID")
  private String assetID = null;

  @JsonProperty("AssetName")
  private String assetName = null;

  @JsonProperty("Level")
  private String level = null;

  @JsonProperty("Variable")
  private String variable = null;

  @JsonProperty("DateTime")
  private DateTime dateTime = null;

  @JsonProperty("SetorCodigo")
  private Long setorCodigo = null;

  public AssetNotificationLog assetID(String assetID) {
    this.assetID = assetID;
    return this;
  }

   /**
   * Get assetID
   * @return assetID
  **/
  @ApiModelProperty(value = "")
  public String getAssetID() {
    return assetID;
  }

  public void setAssetID(String assetID) {
    this.assetID = assetID;
  }

  public AssetNotificationLog assetName(String assetName) {
    this.assetName = assetName;
    return this;
  }

   /**
   * Get assetName
   * @return assetName
  **/
  @ApiModelProperty(value = "")
  public String getAssetName() {
    return assetName;
  }

  public void setAssetName(String assetName) {
    this.assetName = assetName;
  }

  public AssetNotificationLog level(String level) {
    this.level = level;
    return this;
  }

   /**
   * Get level
   * @return level
  **/
  @ApiModelProperty(value = "")
  public String getLevel() {
    return level;
  }

  public void setLevel(String level) {
    this.level = level;
  }

  public AssetNotificationLog variable(String variable) {
    this.variable = variable;
    return this;
  }

   /**
   * Get variable
   * @return variable
  **/
  @ApiModelProperty(value = "")
  public String getVariable() {
    return variable;
  }

  public void setVariable(String variable) {
    this.variable = variable;
  }

  public AssetNotificationLog dateTime(DateTime dateTime) {
    this.dateTime = dateTime;
    return this;
  }

   /**
   * Get dateTime
   * @return dateTime
  **/
  @ApiModelProperty(value = "")
  public DateTime getDateTime() {
    return dateTime;
  }

  public void setDateTime(DateTime dateTime) {
    this.dateTime = dateTime;
  }

  public AssetNotificationLog setorCodigo(Long setorCodigo) {
    this.setorCodigo = setorCodigo;
    return this;
  }

   /**
   * Get setorCodigo
   * @return setorCodigo
  **/
  @ApiModelProperty(value = "")
  public Long getSetorCodigo() {
    return setorCodigo;
  }

  public void setSetorCodigo(Long setorCodigo) {
    this.setorCodigo = setorCodigo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetNotificationLog assetNotificationLog = (AssetNotificationLog) o;
    return Objects.equals(this.assetID, assetNotificationLog.assetID) &&
        Objects.equals(this.assetName, assetNotificationLog.assetName) &&
        Objects.equals(this.level, assetNotificationLog.level) &&
        Objects.equals(this.variable, assetNotificationLog.variable) &&
        Objects.equals(this.dateTime, assetNotificationLog.dateTime) &&
        Objects.equals(this.setorCodigo, assetNotificationLog.setorCodigo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetID, assetName, level, variable, dateTime, setorCodigo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetNotificationLog {\n");
    
    sb.append("    assetID: ").append(toIndentedString(assetID)).append("\n");
    sb.append("    assetName: ").append(toIndentedString(assetName)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    variable: ").append(toIndentedString(variable)).append("\n");
    sb.append("    dateTime: ").append(toIndentedString(dateTime)).append("\n");
    sb.append("    setorCodigo: ").append(toIndentedString(setorCodigo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

