/*
 * api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package logic.smartmind.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;

/**
 * ParamVariavelNotificacao2
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-05-25T12:20:00.812-03:00")
public class ParamVariavelNotificacao2 {
  @JsonProperty("entityID")
  private String entityID = null;

  @JsonProperty("variavel")
  private String variavel = null;

  @JsonProperty("maxAlerta")
  private BigDecimal maxAlerta = null;

  @JsonProperty("maxAviso")
  private BigDecimal maxAviso = null;

  @JsonProperty("minAviso")
  private BigDecimal minAviso = null;

  @JsonProperty("minAlerta")
  private BigDecimal minAlerta = null;

  @JsonProperty("aspectName")
  private String aspectName = null;

  @JsonProperty("lastTimeSeries")
  private String lastTimeSeries = null;

  @JsonProperty("unit")
  private String unit = null;

  @JsonProperty("GerarOSAviso")
  private Boolean gerarOSAviso = null;

  @JsonProperty("GerarOSAlerta")
  private Boolean gerarOSAlerta = null;

  @JsonProperty("GerarSMSAviso")
  private Boolean gerarSMSAviso = null;

  @JsonProperty("GerarSMSAlerta")
  private Boolean gerarSMSAlerta = null;

  @JsonProperty("tempoEsperaNotificacaoSMS")
  private Long tempoEsperaNotificacaoSMS = null;

  @JsonProperty("tempoEsperaNotificacaoEmail")
  private Long tempoEsperaNotificacaoEmail = null;

  @JsonProperty("EnviaEmailAviso")
  private Boolean enviaEmailAviso = null;

  @JsonProperty("EnviaEmailAlerta")
  private Boolean enviaEmailAlerta = null;

  public ParamVariavelNotificacao2 entityID(String entityID) {
    this.entityID = entityID;
    return this;
  }

   /**
   * Get entityID
   * @return entityID
  **/
  @ApiModelProperty(value = "")
  public String getEntityID() {
    return entityID;
  }

  public void setEntityID(String entityID) {
    this.entityID = entityID;
  }

  public ParamVariavelNotificacao2 variavel(String variavel) {
    this.variavel = variavel;
    return this;
  }

   /**
   * Get variavel
   * @return variavel
  **/
  @ApiModelProperty(value = "")
  public String getVariavel() {
    return variavel;
  }

  public void setVariavel(String variavel) {
    this.variavel = variavel;
  }

  public ParamVariavelNotificacao2 maxAlerta(BigDecimal maxAlerta) {
    this.maxAlerta = maxAlerta;
    return this;
  }

   /**
   * Get maxAlerta
   * @return maxAlerta
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMaxAlerta() {
    return maxAlerta;
  }

  public void setMaxAlerta(BigDecimal maxAlerta) {
    this.maxAlerta = maxAlerta;
  }

  public ParamVariavelNotificacao2 maxAviso(BigDecimal maxAviso) {
    this.maxAviso = maxAviso;
    return this;
  }

   /**
   * Get maxAviso
   * @return maxAviso
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMaxAviso() {
    return maxAviso;
  }

  public void setMaxAviso(BigDecimal maxAviso) {
    this.maxAviso = maxAviso;
  }

  public ParamVariavelNotificacao2 minAviso(BigDecimal minAviso) {
    this.minAviso = minAviso;
    return this;
  }

   /**
   * Get minAviso
   * @return minAviso
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMinAviso() {
    return minAviso;
  }

  public void setMinAviso(BigDecimal minAviso) {
    this.minAviso = minAviso;
  }

  public ParamVariavelNotificacao2 minAlerta(BigDecimal minAlerta) {
    this.minAlerta = minAlerta;
    return this;
  }

   /**
   * Get minAlerta
   * @return minAlerta
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMinAlerta() {
    return minAlerta;
  }

  public void setMinAlerta(BigDecimal minAlerta) {
    this.minAlerta = minAlerta;
  }

  public ParamVariavelNotificacao2 aspectName(String aspectName) {
    this.aspectName = aspectName;
    return this;
  }

   /**
   * Get aspectName
   * @return aspectName
  **/
  @ApiModelProperty(value = "")
  public String getAspectName() {
    return aspectName;
  }

  public void setAspectName(String aspectName) {
    this.aspectName = aspectName;
  }

  public ParamVariavelNotificacao2 lastTimeSeries(String lastTimeSeries) {
    this.lastTimeSeries = lastTimeSeries;
    return this;
  }

   /**
   * Get lastTimeSeries
   * @return lastTimeSeries
  **/
  @ApiModelProperty(value = "")
  public String getLastTimeSeries() {
    return lastTimeSeries;
  }

  public void setLastTimeSeries(String lastTimeSeries) {
    this.lastTimeSeries = lastTimeSeries;
  }

  public ParamVariavelNotificacao2 unit(String unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @ApiModelProperty(value = "")
  public String getUnit() {
    return unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }

  public ParamVariavelNotificacao2 gerarOSAviso(Boolean gerarOSAviso) {
    this.gerarOSAviso = gerarOSAviso;
    return this;
  }

   /**
   * Get gerarOSAviso
   * @return gerarOSAviso
  **/
  @ApiModelProperty(value = "")
  public Boolean getGerarOSAviso() {
    return gerarOSAviso;
  }

  public void setGerarOSAviso(Boolean gerarOSAviso) {
    this.gerarOSAviso = gerarOSAviso;
  }

  public ParamVariavelNotificacao2 gerarOSAlerta(Boolean gerarOSAlerta) {
    this.gerarOSAlerta = gerarOSAlerta;
    return this;
  }

   /**
   * Get gerarOSAlerta
   * @return gerarOSAlerta
  **/
  @ApiModelProperty(value = "")
  public Boolean getGerarOSAlerta() {
    return gerarOSAlerta;
  }

  public void setGerarOSAlerta(Boolean gerarOSAlerta) {
    this.gerarOSAlerta = gerarOSAlerta;
  }

  public ParamVariavelNotificacao2 gerarSMSAviso(Boolean gerarSMSAviso) {
    this.gerarSMSAviso = gerarSMSAviso;
    return this;
  }

   /**
   * Get gerarSMSAviso
   * @return gerarSMSAviso
  **/
  @ApiModelProperty(value = "")
  public Boolean getGerarSMSAviso() {
    return gerarSMSAviso;
  }

  public void setGerarSMSAviso(Boolean gerarSMSAviso) {
    this.gerarSMSAviso = gerarSMSAviso;
  }

  public ParamVariavelNotificacao2 gerarSMSAlerta(Boolean gerarSMSAlerta) {
    this.gerarSMSAlerta = gerarSMSAlerta;
    return this;
  }

   /**
   * Get gerarSMSAlerta
   * @return gerarSMSAlerta
  **/
  @ApiModelProperty(value = "")
  public Boolean getGerarSMSAlerta() {
    return gerarSMSAlerta;
  }

  public void setGerarSMSAlerta(Boolean gerarSMSAlerta) {
    this.gerarSMSAlerta = gerarSMSAlerta;
  }

  public ParamVariavelNotificacao2 tempoEsperaNotificacaoSMS(Long tempoEsperaNotificacaoSMS) {
    this.tempoEsperaNotificacaoSMS = tempoEsperaNotificacaoSMS;
    return this;
  }

   /**
   * Get tempoEsperaNotificacaoSMS
   * @return tempoEsperaNotificacaoSMS
  **/
  @ApiModelProperty(value = "")
  public Long getTempoEsperaNotificacaoSMS() {
    return tempoEsperaNotificacaoSMS;
  }

  public void setTempoEsperaNotificacaoSMS(Long tempoEsperaNotificacaoSMS) {
    this.tempoEsperaNotificacaoSMS = tempoEsperaNotificacaoSMS;
  }

  public ParamVariavelNotificacao2 tempoEsperaNotificacaoEmail(Long tempoEsperaNotificacaoEmail) {
    this.tempoEsperaNotificacaoEmail = tempoEsperaNotificacaoEmail;
    return this;
  }

   /**
   * Get tempoEsperaNotificacaoEmail
   * @return tempoEsperaNotificacaoEmail
  **/
  @ApiModelProperty(value = "")
  public Long getTempoEsperaNotificacaoEmail() {
    return tempoEsperaNotificacaoEmail;
  }

  public void setTempoEsperaNotificacaoEmail(Long tempoEsperaNotificacaoEmail) {
    this.tempoEsperaNotificacaoEmail = tempoEsperaNotificacaoEmail;
  }

  public ParamVariavelNotificacao2 enviaEmailAviso(Boolean enviaEmailAviso) {
    this.enviaEmailAviso = enviaEmailAviso;
    return this;
  }

   /**
   * Get enviaEmailAviso
   * @return enviaEmailAviso
  **/
  @ApiModelProperty(value = "")
  public Boolean getEnviaEmailAviso() {
    return enviaEmailAviso;
  }

  public void setEnviaEmailAviso(Boolean enviaEmailAviso) {
    this.enviaEmailAviso = enviaEmailAviso;
  }

  public ParamVariavelNotificacao2 enviaEmailAlerta(Boolean enviaEmailAlerta) {
    this.enviaEmailAlerta = enviaEmailAlerta;
    return this;
  }

   /**
   * Get enviaEmailAlerta
   * @return enviaEmailAlerta
  **/
  @ApiModelProperty(value = "")
  public Boolean getEnviaEmailAlerta() {
    return enviaEmailAlerta;
  }

  public void setEnviaEmailAlerta(Boolean enviaEmailAlerta) {
    this.enviaEmailAlerta = enviaEmailAlerta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParamVariavelNotificacao2 paramVariavelNotificacao2 = (ParamVariavelNotificacao2) o;
    return Objects.equals(this.entityID, paramVariavelNotificacao2.entityID) &&
        Objects.equals(this.variavel, paramVariavelNotificacao2.variavel) &&
        Objects.equals(this.maxAlerta, paramVariavelNotificacao2.maxAlerta) &&
        Objects.equals(this.maxAviso, paramVariavelNotificacao2.maxAviso) &&
        Objects.equals(this.minAviso, paramVariavelNotificacao2.minAviso) &&
        Objects.equals(this.minAlerta, paramVariavelNotificacao2.minAlerta) &&
        Objects.equals(this.aspectName, paramVariavelNotificacao2.aspectName) &&
        Objects.equals(this.lastTimeSeries, paramVariavelNotificacao2.lastTimeSeries) &&
        Objects.equals(this.unit, paramVariavelNotificacao2.unit) &&
        Objects.equals(this.gerarOSAviso, paramVariavelNotificacao2.gerarOSAviso) &&
        Objects.equals(this.gerarOSAlerta, paramVariavelNotificacao2.gerarOSAlerta) &&
        Objects.equals(this.gerarSMSAviso, paramVariavelNotificacao2.gerarSMSAviso) &&
        Objects.equals(this.gerarSMSAlerta, paramVariavelNotificacao2.gerarSMSAlerta) &&
        Objects.equals(this.tempoEsperaNotificacaoSMS, paramVariavelNotificacao2.tempoEsperaNotificacaoSMS) &&
        Objects.equals(this.tempoEsperaNotificacaoEmail, paramVariavelNotificacao2.tempoEsperaNotificacaoEmail) &&
        Objects.equals(this.enviaEmailAviso, paramVariavelNotificacao2.enviaEmailAviso) &&
        Objects.equals(this.enviaEmailAlerta, paramVariavelNotificacao2.enviaEmailAlerta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityID, variavel, maxAlerta, maxAviso, minAviso, minAlerta, aspectName, lastTimeSeries, unit, gerarOSAviso, gerarOSAlerta, gerarSMSAviso, gerarSMSAlerta, tempoEsperaNotificacaoSMS, tempoEsperaNotificacaoEmail, enviaEmailAviso, enviaEmailAlerta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParamVariavelNotificacao2 {\n");
    
    sb.append("    entityID: ").append(toIndentedString(entityID)).append("\n");
    sb.append("    variavel: ").append(toIndentedString(variavel)).append("\n");
    sb.append("    maxAlerta: ").append(toIndentedString(maxAlerta)).append("\n");
    sb.append("    maxAviso: ").append(toIndentedString(maxAviso)).append("\n");
    sb.append("    minAviso: ").append(toIndentedString(minAviso)).append("\n");
    sb.append("    minAlerta: ").append(toIndentedString(minAlerta)).append("\n");
    sb.append("    aspectName: ").append(toIndentedString(aspectName)).append("\n");
    sb.append("    lastTimeSeries: ").append(toIndentedString(lastTimeSeries)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    gerarOSAviso: ").append(toIndentedString(gerarOSAviso)).append("\n");
    sb.append("    gerarOSAlerta: ").append(toIndentedString(gerarOSAlerta)).append("\n");
    sb.append("    gerarSMSAviso: ").append(toIndentedString(gerarSMSAviso)).append("\n");
    sb.append("    gerarSMSAlerta: ").append(toIndentedString(gerarSMSAlerta)).append("\n");
    sb.append("    tempoEsperaNotificacaoSMS: ").append(toIndentedString(tempoEsperaNotificacaoSMS)).append("\n");
    sb.append("    tempoEsperaNotificacaoEmail: ").append(toIndentedString(tempoEsperaNotificacaoEmail)).append("\n");
    sb.append("    enviaEmailAviso: ").append(toIndentedString(enviaEmailAviso)).append("\n");
    sb.append("    enviaEmailAlerta: ").append(toIndentedString(enviaEmailAlerta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

